### ISSUE TITLE
mqtt-streaming unit tests fail a lot

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-connectors#148]
Other connector tests fail some times too but mqtt-streaming is causing biggest issues.

This test is failing the most:
```
[info] - should produce a duplicate publish on the server given two client connections *** FAILED *** (6 seconds, 82 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (6 seconds) during expectMsg while waiting for ByteString(32, 2, 0, 0)
```

**Comment by mdedetrich** [comment]
So just as a heads up, even with https://github.com/apache/incubator-pekko-connectors/pull/196 merged the tests are still flaky so it looks like we have to go to the drawing board again
