### ISSUE TITLE
support Scala3 for S3 connector

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-connectors#166]
Main blocker is that https://github.com/johanandren/futiles has no Scala 3 support. This lib is used in the test code.

fyi @mdedetrich - you appear to be a contributor to 'futiles'

**Comment by mdedetrich** [comment]
> Main blocker is that https://github.com/johanandren/futiles has no Scala 3 support. This lib is used in the test code.
> 
> fyi @mdedetrich - you appear to be a contributor to 'futiles'

Yes that is true however it is maintained by an Akka/Lightbend employer which is why I avoided touching it so far.


I might be overthinking this, nothing physically is stopping me from adding Scala 3 support to it and if it gets ignored then I can always fork it.

**Comment by pjfanning** [comment]
@mdedetrich I've copied the code that we need in https://github.com/apache/incubator-pekko-connectors/pull/167
