### ISSUE TITLE
upgrade datastax dependency

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-connectors#201]
We currently use 4.15.0 of https://mvnrepository.com/artifact/com.datastax.oss/java-driver-core

This has a dependency on Jackson that has CVEs. Also netty dependency with CVEs.

I propose upgrading to 4.17.0. But we probably need to add an explicit dependency on jackson because datastax 4.17.0 still relies on a Jackson release with CVEs (newer but not new enough).

@mdedetrich @nvollmar wdyt?

**Comment by nvollmar** [comment]
I think we should keep 4.15.0 until we can do some more extensive testing with the new driver. 

Meanwhile excluding the dependency and adding an explicit dependency to match the versions used in other Pekko projects would make sense.
