### ISSUE TITLE
Maven release of pekko-connectors

### ISSUE THREAD

**Issue by taher-cldcvr** [apache/incubator-pekko-connectors#210]
Hi All, please can you guys release this on maven repo? I cannot find pekko-connectors. If it is already released please can someone guide me where i can find them? I need to use the pekko-slick connector for JDBC interaction.

Thanks.

**Comment by pjfanning** [comment]
It will take another few weeks to release the jars for this repo.

In the mean time, there are snapshot jars - see https://pekko.apache.org/docs/pekko-connectors/current/other-docs/snapshots.html

The release order is described at https://cwiki.apache.org/confluence/display/PEKKO/Pekko+Module+Release+Order

One option would be to just copy the Slick connector code into your own code base. This saves you from having to wait for an official release.

**Comment by taher-cldcvr** [comment]
Has a release been made yet?

**Comment by pjfanning** [comment]
Not yet. Releases are discussed here: https://lists.apache.org/list.html?dev@pekko.apache.org

**Comment by pjfanning** [comment]
The specific discussion is at https://lists.apache.org/thread/gd4mhjf5zfd4gcdzcv92jsfy5hnv2ggg

If we don't get many responses on that mail thread, the default position will be to wait a few more weeks before starting the release process.

All the important dependencies of this repo are now released - so anyone who needs a connector now can copy the code into their own projects - in the absence of an official release.

**Comment by majk-p** [comment]
Thanks @pjfanning !

I tried to submit my input but it seems I need account to or an email in apache domain.

I just wanted to say I'd also love to have 1.0.0 released, since we already have pekko based module in https://github.com/ocadotechnology/pass4s. Its currently based on nightly build and is considered experimental.

**Comment by pjfanning** [comment]
@majk-p We need emails, I'm afraid. Signing up and responding to the email thread is straightforward. Send an email to dev-subscribe@pekko.apache.org and then you should be able to participate in discussions on that dev list.

**Comment by majk-p** [comment]
Thanks! Just posted there as well. Let me know if you got it. I got follow up responses but my message isn't visible on the tracker you linked.

**Comment by mdedetrich** [comment]
> Thanks! Just posted there as well. Let me know if you got it. I got follow up responses but my message isn't visible on the tracker you linked.

Your email was received, there may be a bit of a delay before its reflected in the Apache Mail Archives (aka PonyMail)
