### ISSUE TITLE
FTP: Server encoding detection

### ISSUE THREAD

**Issue by TheDeadOne** [apache/incubator-pekko-connectors#216]
### Short description

Enable automatic FTP server encoding detection.

### Details

`org.apache.commons.net.ftp.FTPClient` has a `setAutodetectUTF8` method to determine if the server supports UTF-8. Enabling the detection on client creation would allow working with files that have non-Latin names.

**Comment by pjfanning** [comment]
@TheDeadOne would you be interested in submitting a PR? The changes are similar enough to what you already did in your other FTPS PR.

**Comment by TheDeadOne** [comment]
@pjfanning I can add this option to the settings but don't know how it can be tested.

**Comment by pjfanning** [comment]
> @pjfanning I can add this option to the settings but don't know how it can be tested.

Sure. We can probably live with having no test for this.

**Comment by TheDeadOne** [comment]
Okay, I'll do it on the weekend.
