### ISSUE TITLE
upgrade protobuf-java dependencies due to CVEs

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-connectors#222]
The Google BigQuery Storage and Google Pub/Sub gRPC connectors use protobuf-java due to the gRPC libs they use. The version of the gRPC libs we use is a bit old and defaults to protobuf-java 3.21.1. This version has CVEs. Let's use 3.21.12 instead (latest 3.21.x release as of Aug 2023).

**Comment by rafalmag** [comment]
Thanks @pjfanning for working on Pekko connectors. I see #230 PR is merged, thus can this issue be closed? As it is the last open issue for 1.0.0 milestone, when could we expect the connectors release to maven repo?

**Comment by pjfanning** [comment]
closing as #230 is done

@rafalmag Releases in the ASF take a while because they require votes. This is best followed at https://lists.apache.org/list.html?dev@pekko.apache.org

The TLDR is that the Pekko Connectors release could happen tonight but it should happen soon.

See in particular, these mail threads:
* https://lists.apache.org/thread/xz3yzlwlb5bwp9b6xsm9q5gwldo2n1ym
* https://lists.apache.org/thread/9xpdbkl1tzlkpcwnh5qts7h08v92sggk
* https://lists.apache.org/thread/14rmocpqvpr4hpo1yd1fhh1lh6w6bplr
