### ISSUE TITLE
Add Scala3 support for Mongodb driver

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-connectors#228]
It looks like adding Scala 3 support for the Mongodb driver will take a while. For starters the current mongo driver being used isn't supported (see https://github.com/mongodb/mongo-scala-driver) and it has since been moved to https://github.com/mongodb/mongo-java-driver which isn't building for Scala 3.

The main https://github.com/mongodb/mongo-java-driver uses gradle as a build tool, and while the main `scala` gradle plugin supports Scala 3 the project also happens to use [gradle-scala-multiversion-plugin](gradle-scala-multiversion-plugin) since the main default Gradle scala plugin doesn't support proper cross publishing amongst multiple Scala versions. The gradle-scala-multiversion however doesn't support Scala 3 yet (see https://github.com/ADTRAN/gradle-scala-multiversion-plugin/pull/40)

**Comment by pjfanning** [comment]
This is a duplicate of #150

**Comment by mdedetrich** [comment]
Thanks, closing
