### ISSUE TITLE
statefulMapConcat is used but has been deprecated in pekko-streams

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-connectors#294]
@kerr any interest in updating the code in this repo to avoid the deprecated code?

**Comment by mdedetrich** [comment]
I can handle this one

**Comment by pjfanning** [comment]
I think this would be nice to have in v1.0.2 but if needs be, it can kept back till v1.1.0.

**Comment by pjfanning** [comment]
not worth blocking v1.0.2 for this

**Comment by mdedetrich** [comment]
Lets stick with 1.1.0

**Comment by He-Pin** [comment]
I assigned this to you @mdedetrich :) 
I just took a look at the code, there are 6 places.

**Comment by mdedetrich** [comment]
> @mdedetrich Do you still have interest in handling this?

If you want to do this go ahead, I have a lot of other stuff on my plate right now

**Comment by He-Pin** [comment]
OK, I will take a look at it this weekend ,and will back my hometone then.

**Comment by pjfanning** [comment]
https://github.com/apache/incubator-pekko-connectors/pull/330
