### ISSUE TITLE
Replace `statefulMapConcat` with `statefulMap` + `mapConcat` in codebase

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-connectors#307]
As the title suggests, `statefulMapConcat` is deprecated so it should replaced with `statefulMap` + `mapConcat` so that the 1.1.0 version of pekko-http isn't relying on deprecated pekko methods.

**Comment by pjfanning** [comment]
duplicate of https://github.com/apache/incubator-pekko-connectors/issues/294
